#!/usr/bin/env python3
"""
tools/gitlab_fixture_repos.py — manage GitLab repos that mirror evaluation fixtures.

Each fixture (evaluation/fixtures/FXX-name/) becomes one GitLab project under
the configured namespace, with:

  - the contents of source/ flattened to repo root
  - a .gitlab-ci.yml that runs `pytest`
  - main holding the buggy state (the first push triggers a failed pipeline,
    which fires the configured webhook into the SDLCMA gateway)

The script is configuration-driven so the same code works against any GitLab
instance / account / fixtures set: pass --gitlab-url, --token, --namespace,
--fixtures-dir, --prefix. Defaults target the bundled gitlab.com test
account (lishu20161) and evaluation/fixtures/.

Subcommands:
  setup            ensure each fixture project exists, (re)push main to the
                   buggy state, and (re)point its webhook at --webhook-url
  update-webhook   only PUT --webhook-url on every fixture project (cheap;
                   use after a cloudflared restart picks a new URL)
  list             show project_path → project_id for all fixture repos
  teardown         delete fixture repos (default dry-run; pass --yes to delete)

Why force-push main: the worker's bug-fix pipeline anchors on
`base_branch="main"` (ensure_base_branch / create_fix_branch / fetch_file /
gitlab_create_merge_request — see bf_worker/providers/gitlab_provider.py), so
the failing pipeline must be on main; the easiest way to guarantee that is
to make main itself the buggy state.
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
from pathlib import Path

import requests

LOG = logging.getLogger("gitlab_fixture_repos")

DEFAULT_GITLAB_URL = "https://gitlab.com"
DEFAULT_NAMESPACE = "lishu20161"
DEFAULT_PREFIX = "sdlcma-fix-"
DEFAULT_FIXTURES_DIR = Path(__file__).resolve().parents[1] / "evaluation" / "fixtures"

CI_YML = """\
# Auto-generated by tools/gitlab_fixture_repos.py — buggy fixture repo for SDLCMA smoke testing.
stages: [test]

test:
  image: python:3.11-slim
  stage: test
  before_script:
    - pip install --quiet pytest
  script:
    - pytest -q
"""


def fixture_to_project_name(prefix: str, fixture_dirname: str) -> str:
    return prefix + fixture_dirname.lower()


def discover_fixtures(fixtures_dir: Path, filter_ids: list[str] | None = None) -> list[Path]:
    if not fixtures_dir.exists():
        raise SystemExit(f"fixtures-dir not found: {fixtures_dir}")
    out = []
    for f in sorted(fixtures_dir.iterdir()):
        if not f.is_dir() or not (f / "source").is_dir():
            continue
        if filter_ids:
            short_id = f.name.split("-", 1)[0]
            if short_id not in filter_ids and f.name not in filter_ids:
                continue
        out.append(f)
    return out


def gitlab_api(method: str, url: str, token: str, **kw):
    headers = kw.pop("headers", {})
    headers["PRIVATE-TOKEN"] = token
    return requests.request(method, url, headers=headers, timeout=30, **kw)


def find_project(api: str, token: str, namespace: str, name: str) -> dict | None:
    enc = urllib.parse.quote(f"{namespace}/{name}", safe="")
    r = gitlab_api("GET", f"{api}/projects/{enc}", token)
    if r.status_code == 200:
        return r.json()
    if r.status_code == 404:
        return None
    raise SystemExit(f"GET project failed [{r.status_code}]: {r.text[:200]}")


def resolve_namespace_id(api: str, token: str, namespace: str) -> int:
    r = gitlab_api("GET", f"{api}/namespaces", token, params={"search": namespace})
    r.raise_for_status()
    for n in r.json():
        if n.get("path") == namespace or n.get("full_path") == namespace:
            return n["id"]
    raise SystemExit(f"namespace not found: {namespace}")


def create_project(api: str, token: str, namespace_id: int, name: str) -> dict:
    payload = {
        "name": name,
        "path": name,
        "namespace_id": namespace_id,
        "visibility": "private",
        "initialize_with_readme": False,
        "default_branch": "main",
    }
    r = gitlab_api("POST", f"{api}/projects", token, json=payload)
    if r.status_code in (200, 201):
        return r.json()
    raise SystemExit(f"create project {name} failed [{r.status_code}]: {r.text[:300]}")


def delete_project(api: str, token: str, project_id: int) -> bool:
    r = gitlab_api("DELETE", f"{api}/projects/{project_id}", token)
    return r.status_code in (200, 202, 204)


def unprotect_main(api: str, token: str, project_id: int) -> None:
    # New projects have main marked as protected; force-push needs it unprotected.
    gitlab_api("DELETE", f"{api}/projects/{project_id}/protected_branches/main", token)


def push_fixture_to_main(project: dict, fixture_dir: Path, token: str) -> str:
    src = fixture_dir / "source"
    repo_url = project["http_url_to_repo"]
    auth_url = re.sub(r"^https://", f"https://oauth2:{token}@", repo_url)
    workdir = Path(tempfile.mkdtemp(prefix=f"sdlcma-fix-{fixture_dir.name}-"))
    try:
        for entry in src.iterdir():
            dst = workdir / entry.name
            if entry.is_dir():
                shutil.copytree(entry, dst)
            else:
                shutil.copy2(entry, dst)
        (workdir / ".gitlab-ci.yml").write_text(CI_YML)

        def run(*args):
            subprocess.run(args, cwd=workdir, check=True, capture_output=True)

        run("git", "init", "-b", "main")
        run("git", "config", "user.email", "sdlcma-fixtures@example.com")
        run("git", "config", "user.name", "sdlcma-fixtures")
        run("git", "add", ".")
        run("git", "commit", "-m", f"fixture {fixture_dir.name} (buggy)")
        run("git", "remote", "add", "origin", auth_url)
        run("git", "push", "--force", "origin", "main")
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=workdir, capture_output=True, text=True
        )
        return out.stdout.strip()
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def ensure_webhook(api: str, token: str, project_id: int, webhook_url: str) -> int:
    r = gitlab_api("GET", f"{api}/projects/{project_id}/hooks", token)
    r.raise_for_status()
    payload = {
        "url": webhook_url,
        "pipeline_events": True,
        "push_events": False,
        "merge_requests_events": False,
    }
    for h in r.json():
        rr = gitlab_api(
            "PUT", f"{api}/projects/{project_id}/hooks/{h['id']}", token, json=payload
        )
        if rr.status_code in (200, 201):
            return h["id"]
    rr = gitlab_api("POST", f"{api}/projects/{project_id}/hooks", token, json=payload)
    rr.raise_for_status()
    return rr.json()["id"]


def list_fixture_projects(api: str, token: str, prefix: str) -> list[dict]:
    r = gitlab_api(
        "GET",
        f"{api}/projects",
        token,
        params={"search": prefix, "owned": "true", "simple": "true", "per_page": 100},
    )
    r.raise_for_status()
    return sorted(
        (p for p in r.json() if p["path"].startswith(prefix)),
        key=lambda p: p["path"],
    )


# ── CLI ─────────────────────────────────────────────────────────────────────


def load_token_default() -> str | None:
    env = os.environ.get("GITLAB_PRIVATE_TOKEN")
    if env:
        return env
    settings_file = Path(__file__).resolve().parents[1] / "settings" / "worker_gitlab_saas.env"
    if settings_file.exists():
        for line in settings_file.read_text().splitlines():
            if line.startswith("GITLAB_PRIVATE_TOKEN="):
                return line.split("=", 1)[1].strip()
    return None


def cmd_setup(args):
    fixtures = discover_fixtures(args.fixtures_dir, args.fixtures)
    print(f"setup: {len(fixtures)} fixture(s) on {args.namespace} via {args.gitlab_url}")
    api = f"{args.gitlab_url}/api/v4"
    ns_id = resolve_namespace_id(api, args.token, args.namespace)
    for fx in fixtures:
        name = fixture_to_project_name(args.prefix, fx.name)
        proj = find_project(api, args.token, args.namespace, name)
        if proj is None:
            print(f"  + create {args.namespace}/{name}")
            proj = create_project(api, args.token, ns_id, name)
        else:
            print(f"  = reuse  {args.namespace}/{name} (id={proj['id']})")
        unprotect_main(api, args.token, proj["id"])
        sha = push_fixture_to_main(proj, fx, args.token)
        hid = ensure_webhook(api, args.token, proj["id"], args.webhook_url)
        print(f"    pushed main @ {sha[:8]}  hook={hid}")


def cmd_update_webhook(args):
    api = f"{args.gitlab_url}/api/v4"
    projs = list_fixture_projects(api, args.token, args.prefix)
    print(f"update-webhook: {len(projs)} project(s) → {args.webhook_url}")
    for p in projs:
        hid = ensure_webhook(api, args.token, p["id"], args.webhook_url)
        print(f"  {p['path_with_namespace']:60s} hook={hid}")


def cmd_list(args):
    api = f"{args.gitlab_url}/api/v4"
    projs = list_fixture_projects(api, args.token, args.prefix)
    for p in projs:
        print(f"  {p['id']:>10}  {p['path_with_namespace']}")
    print(f"total: {len(projs)}")


def cmd_teardown(args):
    api = f"{args.gitlab_url}/api/v4"
    projs = list_fixture_projects(api, args.token, args.prefix)
    print(f"teardown: {len(projs)} project(s)" + ("" if args.yes else " (dry-run; pass --yes)"))
    for p in projs:
        if args.yes:
            ok = delete_project(api, args.token, p["id"])
            print(f"  {'DEL' if ok else 'ERR'}  {p['path_with_namespace']}")
        else:
            print(f"  DRY  {p['path_with_namespace']}")


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Manage GitLab fixture repos for SDLCMA smoke testing",
    )
    p.add_argument("--gitlab-url", default=DEFAULT_GITLAB_URL)
    p.add_argument(
        "--token",
        default=None,
        help="GitLab private token (default: $GITLAB_PRIVATE_TOKEN or settings/worker_gitlab_saas.env)",
    )
    p.add_argument("--namespace", default=DEFAULT_NAMESPACE)
    p.add_argument("--prefix", default=DEFAULT_PREFIX)
    p.add_argument("--fixtures-dir", type=Path, default=DEFAULT_FIXTURES_DIR)
    p.add_argument(
        "--fixtures",
        default=None,
        help="comma list (e.g. F01,F02); default = all under --fixtures-dir",
    )
    p.add_argument("-v", "--verbose", action="store_true")

    sub = p.add_subparsers(dest="cmd", required=True)
    sp = sub.add_parser("setup")
    sp.add_argument("--webhook-url", required=True)
    sp.set_defaults(func=cmd_setup)
    sp = sub.add_parser("update-webhook")
    sp.add_argument("--webhook-url", required=True)
    sp.set_defaults(func=cmd_update_webhook)
    sp = sub.add_parser("list")
    sp.set_defaults(func=cmd_list)
    sp = sub.add_parser("teardown")
    sp.add_argument("--yes", action="store_true", help="actually delete (default = dry-run)")
    sp.set_defaults(func=cmd_teardown)

    args = p.parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO, format="%(message)s"
    )

    if args.token is None:
        args.token = load_token_default()
    if not args.token:
        raise SystemExit("no token: pass --token or set GITLAB_PRIVATE_TOKEN")

    if args.fixtures:
        args.fixtures = [s.strip() for s in args.fixtures.split(",") if s.strip()]

    args.func(args)


if __name__ == "__main__":
    main()
